"use client";

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import ContactPane from "@/components/ContactPane";
import { useSetAtom } from "jotai";
import { useEffect } from "react";
import { userAtom, userLoadingAtom } from "@/states/User";
import { authClient } from "@/lib/auth-client";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sleep = (ms: number) => {
    return new Promise((resolve) => setTimeout(resolve, ms));
  };

  const setUser = useSetAtom(userAtom);
  const setUserLoading = useSetAtom(userLoadingAtom);

  async function getSession() {
    setUserLoading(true);
    const response = await authClient.getSession();
    if (response.error) {
      setUserLoading(false);
      return false;
    }
    await sleep(3000);
    setUser(response.data?.user);
    setUserLoading(false);
  }

  useEffect(() => {
    getSession();
  }, []);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-dvw h-dvh grid grid-cols-1 md:grid-cols-[max-content_1fr] overflow-hidden`}
      >
        <ContactPane></ContactPane>
        {children}
      </body>
    </html>
  );
}
