"use client";

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { useSetAtom } from "jotai";
import { useEffect } from "react";
import { Toaster } from "sonner";
import ContactPane from "@/components/ContactPane";
import { authClient } from "@/lib/auth-client";
import { userAtom, userLoadingAtom } from "@/states/User";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const setUser = useSetAtom(userAtom);
  const setUserLoading = useSetAtom(userLoadingAtom);

  useEffect(() => {
    const getSession = async () => {
      setUserLoading(true);
      const response = await authClient.getSession();
      if (response.error) {
        setUserLoading(false);
        return;
      }
      await new Promise((resolve) => setTimeout(resolve, 3000));
      setUser(response.data?.user);
      setUserLoading(false);
    };

    void getSession();
  }, [setUser, setUserLoading]);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-dvw h-dvh grid grid-cols-1 md:grid-cols-[max-content_1fr] overflow-hidden`}
      >
        <ContactPane></ContactPane>
        {children}
        <div className="absolute">
          <Toaster richColors position="top-center" />
        </div>
      </body>
    </html>
  );
}
